### ISSUE TITLE
does #when:is work in Pharo 7?

### ISSUE THREAD

**Issue by macta** [dionisiydk/Mocketry#7]
Just tried the following example from the docs and it seems to always pass?

| mock flag |
mock := Mock new.
mock someMessage
    when: [flag] is: true.
    
flag := false.
mock someMessage. "will fail immediately on call by last condition: flag should be true"

**Comment by macta** [comment]
I was thinking this construct might give me a building block for an #expect like construct where a mock might fail at the point of execution if some conditions are met (vs. failing post execution).

**Comment by dionisiydk** [comment]
Hi Tim.

You forgot #stub message to mock. Any extectations are defined like that:


mock stub someMessage when: [flag] is: true.

The reason why it does not fail is because Mocketry follows what I would
call modern mocks practice: do not fail when new message is received, every
restriction should be explicitly defined. It makes test with mocks less
brittle and reduce dependency on internal details of tested behavior.

I received your another mail about such details. I will answer you there.
(traveling now without reliable internet)

сб, 9 мар. 2019 г. в 01:58, Tim Mackinnon <notifications@github.com>:

**Comment by dionisiydk** [comment]
And thanks to show me documentation bag :)

сб, 9 мар. 2019 г. в 01:58, Tim Mackinnon <notifications@github.com>:

**Comment by macta** [comment]
Denis has explained that this is a documentation bug - its actually:
`mock stub someMessage...`

When the docs are fixed, this can be closed.

**Comment by dionisiydk** [comment]
Seems it can be closed
